name: gemmlowp
vendor: tensorflow
version: "0.4"

pdsc: ./contributions/merge/tensorflow.gemmlowp.pdsc
add:  ./contributions/add
build: build
out: ./

remote_source: #
local_source: ../src/gemmlowp
src_dest: ./src


