name: ethos-u-core-driver
vendor: ARM
version: "0.4"

pdsc: ./contributions/merge/ARM.ethos-u-core-driver.pdsc
add:  ./contributions/add
build: build
out: ./

remote_source: #https://github.com/google/flatbuffers/archive/master.zip
local_source: ../../../tensorflow/tensorflow/lite/micro/tools/make/downloads/ethos_u_core_driver/
src_dest: ./ethos_u_core_driver


