name: kissfft
vendor: tensorflow
version: "0.4"

pdsc: ./contributions/merge/tensorflow.kissfft.pdsc
add:  ./contributions/add
build: build
out: ./

remote_source: #https://github.com/google/flatbuffers/archive/master.zip
local_source: ../src/kissfft
src_dest: ./src


