# This is a basic workflow to help you get started with Actions

name: Create Runtime environment and Build Pack

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # - name: Cache
      #  uses: actions/cache@v2.1.3
      #  with:
      #    path: 
  
      - name: Checkout tensorflow-build 
        uses: actions/checkout@v2
        with: 
          repository: MDK-Packs/tensorflow-pack
          path: tensorflow-pack
         
      - name: Checkout tensorflow
        uses: actions/checkout@v2
        with: 
          repository: tensorflow/tensorflow
          path: tensorflow
          clean: false  

      # Runs a single command using the runners shell
      - name: Build the docker image with CMSIS tools 
        run: |
           cd ${{ github.workspace }}/tensorflow-pack/cmsis_oss_docker/
           docker build --pull --rm -f "Dockerfile" -t cmsisossdocker:latest "."

      - name: Create Container runtime from image
        run : |
          docker run -i -v ${{ github.workspace }}:/workspace/host --name build_runtime  -d cmsisossdocker
          docker exec build_runtime pip3 install six requests
        
           
      - name: Build Pack and run PackChk
        run : |
          docker exec build_runtime python3 /workspace/host/tensorflow-pack/tensorflow-build/generate_cmsis_pack.py  --tensorflow_path=/workspace/host/tensorflow --input_template=/workspace/host/tensorflow-pack/tensorflow-build/template/cmsis_pack.tpl
          
      - name: Execute test suite
        run: echo "Run tests on Cortex-M55 FVP"
        
