# This is a basic workflow to help you get started with Actions

name: Release CI using Arm Virtual Hardware

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      revision:
        description: 'mlplatform revision'     
        required: true
        default: '22.02'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-tensorflow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
  
      - name: Checkout tensorflow-build 
        uses: actions/checkout@v2
        with: 
          repository: MDK-Packs/tensorflow-pack
          path: tensorflow-pack

   #   - name: Create Container runtime from DockerHub
   #     run : |
   #       docker run -i -v ${{ github.workspace }}:/workspace/host --mac-address="00:02:F7:FF:55:55" --name build_runtime -d armswdev/cmsis_tools_m55:latest 
   #       docker exec build_runtime pip3 install six requests pyyaml junit_xml pillow
   #       docker exec build_runtime cp /workspace/host/tensorflow-pack/tensorflow-build/.wgetrc /root/.wgetrc 
   #       mkdir ${{ github.workspace }}/out/
    
      - name: Install tools
        run: |
          sudo apt install rsync
          pip3 install pillow
          mkdir ${{ github.workspace }}/out/
          
      - name: Run the pack build with the revision specified
        run : 
          ./tensorflow-pack/tensorflow-build/build_r.sh ${{ github.event.inputs.revision }} 

      - name: Copy tensorflow-pack to out path
        run :  
          cp ${{ github.workspace }}/tensorflow-pack/tensorflow-build/gen/build/*.pack ${{ github.workspace }}/out/

      - name: Run the 3rdparty pack build with the revision specified
        run : |
          export PATH=$PATH:${{ github.workspace }}/tensorflow-pack/tensorflow-build/gen/utilities
          ./tensorflow-pack/3rdparty-build/build_r.sh ${{ github.event.inputs.revision }} 

      - name: Copy 3rdparty packs to out path
        run :  
          cp ${{ github.workspace }}/tensorflow-pack/3rdparty-build/*.pack ${{ github.workspace }}/out/

      - name: Upload Pack
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/out
        
    #  - name: Upload Test Reports
    #    uses: actions/upload-artifact@v2
    #    with:
    #      path: ${{ github.workspace }}/tensorflow-pack/**/*.junit

